title: Tahnima Akter
description: Student at BRAC University.
baseurl: "/remple/"
url: ""
resume_url: "resume.pdf"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
